/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.igu;

/**
 *
 * @author Martín
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnAdmin2 = new javax.swing.JButton();
        btnEmpleado2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 250, 243));

        btnAdmin2.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        btnAdmin2.setForeground(new java.awt.Color(164, 0, 0));
        btnAdmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/avatar_usuario.png"))); // NOI18N
        btnAdmin2.setText("Administrador");
        btnAdmin2.setBorder(null);
        btnAdmin2.setContentAreaFilled(false);
        btnAdmin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmin2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAdmin2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin2ActionPerformed(evt);
            }
        });

        btnEmpleado2.setBackground(new java.awt.Color(255, 250, 243));
        btnEmpleado2.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        btnEmpleado2.setForeground(new java.awt.Color(164, 0, 0));
        btnEmpleado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/avatar_usuario.png"))); // NOI18N
        btnEmpleado2.setText("Empleado");
        btnEmpleado2.setBorder(null);
        btnEmpleado2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleado2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleado2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEmpleado2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(btnAdmin2)
                .addGap(123, 123, 123)
                .addComponent(btnEmpleado2)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEmpleado2)
                    .addComponent(btnAdmin2))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdmin2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin2;
    private javax.swing.JButton btnEmpleado2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
